solved issue 184. Fixed undefined local variable or method error and added better error handling and messages for text to image convert errors. Used for flickr and vkontakte post where image attactment is required
184) localhost exception:
     filename = /Disk-0/OLAP-hosting/Ruby/railsapps/gofreerev-fb/public/images/temp/5o5bqtwbag.png
     create_png_image_from_text: phandomjs: cmd = phantomjs /Disk-0/OLAP-hosting/Ruby/railsapps/gofreerev-fb/public/images/temp/5o5bqtwbag.js
     create_png_image_from_text: phantomjs: stdout = , stderr = sh: 2: phantomjs: not found
     , status = 127 (Fixnum)
     rescue in generic_post_on_wall: Exception: undefined local variable or method `png_os_path_os_path' for Picture(Table doesn't exist):Class (NameError)
     rescue in generic_post_on_wall: Backtrace: /home/jro/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.0.0/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
     /Disk-0/OLAP-hosting/Ruby/railsapps/gofreerev-fb/app/models/picture.rb:410:in `create_png_image_from_text'
     /Disk-0/OLAP-hosting/Ruby/railsapps/gofreerev-fb/app/controllers/util_controller.rb:2031:in `generic_post_on_wall'